---
title: "FP Graph Code"
author: "MW"
date: "2025-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Import Libraries

```{r Import, echo=TRUE}
# Load Libraries
library(tidyverse)
library(raster)          #raster()
library(sf)              #st_read()
library(ggspatial)       #annotation_scale,annotation_north_arrow
library(ggnewscale)      #new_scale_color() 
library(ggsn)            #scalebar()
library(shiny)           #Shiny app
library(plotly)          #plot_ly()
library(gridExtra)       #grid.arrange()

# Setup Data
setwd("~/FinalProject")
newDS = readRDS("CS_Erate_CrateCombined1.Rds")
newDF = as.data.frame(newDS)
```


## Time Series Plots

```{r TimeSeriesData, echo=TRUE}
#Filter Data for Just the Desired States
timeline = newDF %>%
  filter(NAME=="Indiana" | NAME=="Illinois" | NAME=="Michigan"| NAME=="Ohio" ) %>%
  #Add Day and Month Columns for Date Object Column
  mutate(Day = 1) %>%
  mutate(Month = 1) %>%
  #Add Column for Date Object
  mutate(Date=as.Date(format(as.Date(paste(Day, Month, Year, sep = '.'),"%d.%m.%Y"),"%Y-%m-%d")))
```

```{r TimeSeriesPlotA, echo=TRUE}
#Use the timeline data to plot Unemployment
plot_ly(data=timeline,x=~Date,y=~Unemplyrate,type="scatter",mode="lines",color=~NAME) %>%
  #Adjust Labels and Title
  layout(title="Unemployment Rate Over Time",xaxis=list(title="Year"),yaxis=list(title="Unemployment Rate"))
```

```{r TimeSeriesPlotB, echo=TRUE}
#Use the timeline data to plot Crime
plot_ly(data=timeline,x=~Date,y=~Crimerate,type="scatter",mode="lines",color=~NAME) %>%
  #Adjust Labels and Title
  layout(title="Crime Rate Over Time",xaxis=list(title="Year"),yaxis=list(title="Crime Rate"))
```


## Geospatial Plots

```{r Spatial, echo=TRUE}
# A spatial map of the contiguous US in 2014
geoDF = newDF %>%
  filter(Year == "2014")

#Set Color Palette
mapPal = colorspace::diverge_hcl(20, palette = "Blue-Red")
```

```{r SpatialPlotA, echo=TRUE}
#Unemployment Plot
ggplot() +
  #States Shape
  geom_sf(data=geoDF$geometry,aes(fill=as.factor(floor(geoDF$Unemplyrate))))+
  #Scale Color With Palette
  scale_fill_manual(values = mapPal)+
  #Scale Bar
  annotation_scale(location="bl", width_hint=0.5) +
  #North Arrow
  annotation_north_arrow(location = "bl", which_north = "true",
                         pad_x = unit(0, "in"), pad_y = unit(0.2, "in"),
                         style = north_arrow_fancy_orienteering) +
  #Set Legend Position
  theme(legend.position = "bottom") +
  #Remove Legend Title
  labs(fill = "Unemployment Rate")+
  #Set font size for all texts
  theme(text = element_text(size=20)) +
  #Labels
  xlab("Longitude") + ylab("Latitude") +
  #Title
  ggtitle("2014 Unemplyment Rate Map over Contiguous US")
```

```{r SpatialPlotB, echo=TRUE}
#Crime Plot
ggplot() +
  #States Shape
  geom_sf(data=geoDF$geometry,aes(fill=as.factor(geoDF$Crimerate)))+
  #Scale Color With Palette
  scale_fill_manual(values = mapPal)+
  #Scale Bar
  annotation_scale(location="bl", width_hint=0.5) +
  #North Arrow
  annotation_north_arrow(location = "bl", which_north = "true",
                         pad_x = unit(0, "in"), pad_y = unit(0.2, "in"),
                         style = north_arrow_fancy_orienteering) +
  #Set Legend Position
  theme(legend.position = "bottom") +
  #Remove Legend Title
  labs(fill = "Crime Rate")+
  #Set font size for all texts
  theme(text = element_text(size=20)) +
  #Labels
  xlab("Longitude") + ylab("Latitude") +
  #Title
  ggtitle("2014 Crime Rate Map over Contiguous US")
```


## Scatter Plot

```{r Scatterplot}
# Filter Data for Just 2014
sctr = newDF %>% filter(Year == "2014") 
#Plot Time 
plot_ly(data=sctr,x=~Crimerate,y=~Unemplyrate,type="scatter",mode="markers",color=~REGION) %>%
  layout(title="2014 Crime and Unemployment by Region",xaxis=list(title="Crime Rate per 100 People"),yaxis=list(title="Unemployment Rate per 100 People"))
```